set dotfiles \
    # alacritty
    ~/.config/alacritty/alacritty.yml \
    # bpytop
    ~/.config/bpytop/bpytop.conf \
    # btop
    ~/.config/btop/btop.conf \
    # conda
    ~/.condarc \
    # fish
    ~/.config/fish/config.fish \
    # flake8
    ~/.flake8 \
    # git
    ~/.gitconfig \
    # kitty
    ~/.config/kitty/kitty.conf \
    # nano
    ~/.nanorc \
    # micro
    ~/.config/micro/settings.json \
    ~/.config/micro/bindings.json \
    ~/.config/micro/colorschemes/remi.micro \
    # restic
    ~/.resticignore \
    # spyder
    ~/.spyder-py3/template.py \
    ~/.config/spyder-py3/template.py \
    # sqlfluff
    ~/.sqlfluff \
    # terminator
    ~/.config/terminator/config \
    # tmux
    ~/.tmux.conf \
    # yamlfmt
    ~/.yamlfmt \
