# from https://github.com/romainl/Apprentice

url_color #5F87AF

active_border_color #BCBCBC

inactive_border_color #1C1C1C

active_tab_foreground #1C1C1C
active_tab_background #BCBCBC

inactive_tab_foreground #BCBCBC
inactive_tab_background #1C1C1C

tab_bar_background #1C1C1C

foreground #BCBCBC
background #262626

selection_foreground #262626
selection_background #BCBCBC

## black
color0 #1C1C1C
color8 #444444
## red
color1 #AF5F5F
color9 #FF8700
## green
color2 #5F875F
color10 #87AF87
## yellow
color3 #87875F
color11 #FFFFAF
## blue
color4 #5F87AF
color12 #87AFD7
## magenta
color5 #5F5F87
color13 #8787AF
## cyan
color6 #5F8787
color14 #5FAFAF
## white
color7 #6C6C6C
color15 #FFFFFF

macos_titlebar_color #1C1C1C
