# Fonts
font_family Menlo
font_size 12

disable_ligatures always

# Cursor customization
cursor none
cursor_shape block

# Scrollback
scrollback_lines 10000

# Mouse
url_color #179ae0
url_style straight

copy_on_select yes

strip_trailing_spaces smart

select_by_word_characters _-#

mouse_map left click ungrabbed

# Terminal bell
enable_audio_bell no

# Window layout
enabled_layouts tall,fat,stack

window_border_width 1.5

single_window_margin_width 1.5

placement_strategy top-left

active_border_color #efebe7

inactive_border_color #222b35

# Tab bar
#tab_bar_style slant
tab_bar_style separator
tab_separator ""
tab_title_template " {index} {title} "

active_tab_foreground #222b35
active_tab_background #efebe7
active_tab_font_style normal

inactive_tab_foreground #efebe7
inactive_tab_background #222b35
inactive_tab_font_style normal

tab_bar_background #222b35

# Color scheme
foreground #ffffff
background #19232d

selection_foreground #ffffff
selection_background #1a72bb

## black
color0 #999999
color8 #999999
## red
color1 #ee6772
color9 #ee6772
## green
color2 #b0e686
color10 #b0e686
## yellow
color3 #faed5c
color11 #faed5c
## blue
color4 #57d6e4
color12 #57d6e4
## magenta
color5 #c670e0
color13 #c670e0
## cyan
color6 #57d6e4
color14 #57d6e4
## white
color7 #ffffff
color15 #ffffff

# Advanced
shell /opt/local/bin/fish

update_check_interval 0

startup_session ~/kitty.session

shell_integration disabled

macos_option_as_alt yes
macos_show_window_title_in window
