# Fonts
font_family Source Code Pro
font_size 10

disable_ligatures always

# Cursor customization
cursor none

# Scrollback
scrollback_lines 10000

# Mouse
## (spyder highlight url)
url_color #179ae0
url_style straight

copy_on_select clipboard

strip_trailing_spaces smart

select_by_word_characters _-#

mouse_map left click ungrabbed

# Terminal bell
enable_audio_bell no

# Window layout
enabled_layouts tall,fat,stack

window_border_width 1

single_window_margin_width 1

placement_strategy top-left

## (spyder text normal)
active_border_color #dfe1e2

## (spyder highlight current line)
inactive_border_color #3a424a

hide_window_decorations yes

# Tab bar
tab_bar_style separator
tab_separator " "
tab_title_template " /{title} "

# (spyder highlight current line)
active_tab_foreground #3a424a
## (spyder text normal)
active_tab_background #dfe1e2
active_tab_font_style normal

## (spyder text normal)
inactive_tab_foreground #dfe1e2
## (spyder highlight current line)
inactive_tab_background #3a424a
inactive_tab_font_style normal

## (spyder highlight current line)
tab_bar_background #3a424a

# Color scheme
## (spyder text normal)
foreground #dfe1e2
## (spyder background background)
background #19232d

## (spyder text normal)
selection_foreground #dfe1e2
## (spyder highlight occurence)
selection_background #1a72bb

## black
## (spyder text comment)
color0 #999999
color8 #999999
## red
## (spyder text instance)
color1 #ee6772
color9 #ee6772
## green
## (spyder text string)
color2 #b0e686
color10 #b0e686
## yellow
## (spyder text number)
color3 #faed5c
color11 #faed5c
## blue
## (spyder text definition)
color4 #57d6e4
color12 #57d6e4
## magenta
## (spyder text keyword)
color5 #c670e0
color13 #c670e0
## cyan
## (spyder text definition)
color6 #57d6e4
color14 #57d6e4
## white
## (spyder text normal)
color7 #dfe1e2
color15 #dfe1e2

# Advanced
shell /usr/bin/fish

editor /usr/bin/micro

update_check_interval 0

shell_integration disabled
