include colors.conf

# Fonts
font_family Source Code Pro
font_size 10

disable_ligatures always

# Cursor customization
cursor none

# Scrollback
scrollback_lines 10000

# Mouse
url_style straight

copy_on_select clipboard

strip_trailing_spaces smart

select_by_word_characters _-#

mouse_map left click ungrabbed

# Terminal bell
enable_audio_bell no

# Window layout
enabled_layouts tall,fat,stack

window_border_width 1

single_window_margin_width 1

placement_strategy top-left

hide_window_decorations yes

# Tab bar
tab_bar_style separator
tab_separator " "
tab_title_template " {title} "

active_tab_font_style normal

inactive_tab_font_style normal

# Advanced
shell /usr/bin/fish

editor /usr/bin/micro

update_check_interval 0

shell_integration disabled
